DiamondStore/DiamondStore/Pages/Admin/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BussinessObject.Models;
using BussinessObject.DTO;
using Service.Interface;
using System.Data;
using Service;
using System.ComponentModel.DataAnnotations;
using Microsoft.IdentityModel.Tokens;

namespace DiamondStore.Pages.Admin
{
    public class EditModel : PageModel
    {
        private readonly IUserAccountService _userAccountService;
        private readonly IRoleService _roleService;

        public EditModel(IUserAccountService userAccountService, IRoleService roleService)
        {
            _userAccountService = userAccountService;
            _roleService = roleService;
        }

        [BindProperty]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string email { get; set; }

        [BindProperty]
        public UserDTO user { get; set; } = default!;

        Dictionary<int, string> roles = new Dictionary<int, string>
            {
                { 1, "Customer" },
                { 2, "Shipper" },
                { 3, "Manager" },
                { 4, "Admin" },
                { 5, "Support" }
            };

        public List<string> Status = new List<string> { "Active", "Inactive" };

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            var UserRole = HttpContext.Session.GetInt32("UserRole");
            if (UserRole != 4)
            {
                return Redirect("../Login");
            }

            if (id == null)
            {
                return NotFound();
            }
            //Bắt lỗi validation

             user = await _userAccountService.GetByIdAsyncByAdmin(id.ToString());
            email = user.Email;
            if (user == null)
            {
                return NotFound();
            }


            ViewData["RoleId"] = new SelectList(roles,"Key","Value");
            ViewData["StatusState"] = new SelectList(Status);
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            //if (!ModelState.IsValid)
            //{
            //    return Page();
            //}

            var data = await _userAccountService.GetByIdAsyncByAdmin(user.UserId.ToString());

            if (user.Username != null)
            {
                data.Username = user.Username;
            } 

            if (!email.IsNullOrEmpty())
            {
                data.Email = email;
            }

            if (user.Status != null)
            {
                data.Status = user.Status;
            }


            if (roles.TryGetValue(int.Parse(user.RoleName), out string roleName))
            {
                var role = await _roleService.GetRoleByName(roleName);
                data.RoleId = role.RoleId;
            }


            await _userAccountService.UpdateAsyncByAdmin(data);


            return RedirectToPage("./Index");
        }

        private bool UserExists(Guid id)
        {
            if (_userAccountService.GetByIdAsyncByAdmin(id.ToString()) != null)
            {
                return true;
            }
            return false;

        }
    }
}

DiamondStore/DiamondStore/Pages/DeliveryManagepage/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using BussinessObject.Models;
using Service.Interface;

namespace DiamondStore.Pages.DeliveryManagepage
{
    public class CreateModel : PageModel
    {
        private readonly IDeliverymanagement _context;

        public CreateModel(IDeliverymanagement context)
        {
            _context = context;
        }

        public async Task<IActionResult> OnGet()
        {
            var manager = await _context.GetManagerList();
            var order = await _context.GetOrderList();
            var shipper = await _context.GetShipperList();

            ViewData["ManagerId"] = new SelectList(manager, "UserId", "Email");
        ViewData["OrderId"] = new SelectList(order, "OrderId", "Id");
        ViewData["ShiperId"] = new SelectList(shipper, "UserId", "Email");
            return  Page();
        }

        [BindProperty]
        public Delivery Delivery { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            

            _context.AddAsync(Delivery);
            

            return RedirectToPage("./Index");
        }
    }
}

DiamondStore/DiamondStore/Pages/DeliveryManagepage/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BussinessObject.Models;
using Service.Interface;

namespace DiamondStore.Pages.DeliveryManagepage
{
    public class DeleteModel : PageModel
    {
        private readonly IDeliverymanagement _context;

        public DeleteModel(IDeliverymanagement context)
        {
            _context = context;
        }

        [BindProperty]
        public Delivery Delivery { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var delivery = await _context.GetByIdAsync( id.ToString());

            if (delivery == null)
            {
                return NotFound();
            }
            else
            {
                Delivery = delivery;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var delivery = await _context.GetByIdAsync(id.ToString());
            if (delivery != null)
            {
                Delivery = delivery;
              await  _context.DeleteAsync(id.ToString());
               
            }

            return RedirectToPage("./Index");
        }
    }
}

DiamondStore/DiamondStore/Pages/DeliveryManagepage/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BussinessObject.Models;
using Service.Interface;
using Microsoft.Identity.Client;

namespace DiamondStore.Pages.DeliveryManagepage
{
    public class DetailsModel : PageModel
    {
        private readonly IDeliverymanagement _context;
        private readonly IOrderService _order;

        private readonly IOrderItemService _item;


        public DetailsModel(IDeliverymanagement context, IOrderService service,  IOrderItemService item)
        {
            
            _context = context;
            _order = service;
            _item = item;
        }
        public IList<OrderItem> OrderItem { get; set; }
        public Delivery Delivery { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var delivery = await _context.GetByIdAsync(id.ToString());
            //var Order = await _order.GetByIdAsync(delivery.OrderId.ToString());
            //var manager = await _userAccountService.GetByIdAsync(delivery.ManagerId.ToString());
            //delivery.Manager = manager;
            //var shipper = await _userAccountService.GetByIdAsync(delivery.ShiperId.ToString());
            //delivery.Shiper = shipper;
            //delivery.Order = Order;
            if (delivery.OrderId.HasValue)
            {
                // Lấy danh sách OrderItem theo OrderId
                OrderItem = (await _item.FindAsync(oi => oi.OrderId == delivery.OrderId)).ToList();
            }

            if (delivery == null)
            {
                return NotFound();
            }
            else
            {

                Delivery = delivery;
            }
            return Page();
        }
    }
}

DiamondStore/DiamondStore/Pages/DeliveryManagepage/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BussinessObject.Models;
using Service.Interface;
using Service.Implement;
using DocumentFormat.OpenXml.Office2010.Excel;

namespace DiamondStore.Pages.DeliveryManagepage
{
    public class EditModel : PageModel
    {
        private readonly IDeliverymanagement _context;
        private readonly IUserAccountService _userAccountService;
        // private readonly BussinessObject.Models.DiamondStoreContext _context;

        public EditModel(IDeliverymanagement context, IUserAccountService userAccountService)
        {
            _context = context;
            _userAccountService = userAccountService;
        }

        [BindProperty]
        public Delivery Delivery { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var delivery = await _context.GetByIdAsync(id.ToString());
            if (delivery == null)
            {
                return NotFound();
            }
            Delivery = delivery;
            var manager = await _context.GetManagerList();
            var order = await _context.GetOrderList();
            var shipper = await _context.GetShipperList();
            ViewData["ManagerId"] = new SelectList(manager, "UserId", "Email");
            ViewData["OrderId"] = new SelectList(order, "OrderId", "Id");
            ViewData["ShiperId"] = new SelectList(shipper, "UserId", "Email");

            Delivery = delivery;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {


            //   _context.Attach(Delivery).State = EntityState.Modified;
            var role = HttpContext.Session.GetInt32("UserRole");

            if (role == 2)
            {
                Delivery.Status = "Shipped";
                await _context.UpdateAsync(Delivery);
            }
            else
                try
                {
                    await _context.UpdateAsync(Delivery);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (await DeliveryExists(Delivery.DeliveryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

            return RedirectToPage("./Index");
        }

        private async Task<bool> DeliveryExists(Guid id)
        {
            var exist = await _context.FindAsync(e => e.DeliveryId == id);
            return exist == null;
        }
    }
}

DiamondStore/DiamondStore/Pages/OrderItems/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using BussinessObject.Models;

namespace DiamondStore.Pages.OrderItems
{
    public class CreateModel : PageModel
    {
        private readonly BussinessObject.Models.DiamondStoreContext _context;

        public CreateModel(BussinessObject.Models.DiamondStoreContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        //ViewData["OrderId"] = new SelectList(_context.Orders, "OrderId", "Status");
        //ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "Name");
            return Page();
        }

        [BindProperty]
        public OrderItem OrderItem { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            
            await _context.AddAsync(OrderItem);

            return RedirectToPage("./Index");
        }
    }
}

DiamondStore/DiamondStore/Pages/OrderItems/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BussinessObject.Models;
using Service.Interface;

namespace DiamondStore.Pages.OrderItems
{
    public class DeleteModel : PageModel
    {
        private readonly IOrderItemService _context;

        public DeleteModel(IOrderItemService context)
        {
            _context = context;
        }

        [BindProperty]
        public OrderItem OrderItem { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderitem = await _context.GetByIdAsync(id.ToString());

            if (orderitem == null)
            {
                return NotFound();
            }
            else
            {
                OrderItem = orderitem;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderitem = await _context.GetByIdAsync(id.ToString());

            if (orderitem != null)
            {
                await _context.DeleteAsync(id.ToString());
            }

            return RedirectToPage("./Index");
        }
    }
}

DiamondStore/DiamondStore/Pages/OrderItems/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BussinessObject.Models;
using Service.Interface;

namespace DiamondStore.Pages.OrderItems
{
    public class DetailsModel : PageModel
    {
        private readonly IOrderItemService _context;

        public DetailsModel(IOrderItemService context)
        {
            _context = context;
        }

        public OrderItem OrderItem { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderitem = await _context.GetByIdAsync(id.ToString());

            if (orderitem == null)
            {
                return NotFound();
            }
            else
            {
                OrderItem = orderitem;
            }
            return Page();
        }
    }
}

DiamondStore/DiamondStore/Pages/Products/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BussinessObject.Models;
using Service.Interface;
using Service;
using Service.Dtos;

namespace DiamondStore.Pages.Products
{
    public class IndexModel : PageModel
    {
        private readonly IProductService _productService;
        private readonly IOrderItemService _orderItemService;

        public IndexModel(IProductService productService, IOrderItemService orderItemService)
        {
            _productService = productService;
            _orderItemService = orderItemService;
        }

        public IList<Product> Products { get; set; } = default!;

        public async Task OnGetAsync()
        {
            var products = await _productService.GetAllAsync();
            Products = products.ToList();
        }

        public async Task<IActionResult> OnPostAddToCartAsync(string id)
        {
            var user = HttpContext.Session.GetObjectFromJson<UserDto>("User");
            await _orderItemService.AddProductToOrder(user.userId.ToString(), id);
            return RedirectToPage();
        }
    }
}

DiamondStore/DiamondStore/Pages/Products/Create.cshtml
@page
@model DiamondStore.Pages.Products.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Products.Name" class="control-label"></label>
                <input asp-for="Products.Name" class="form-control" />
                <span asp-validation-for="Products.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Products.Description" class="control-label"></label>
                <input asp-for="Products.Description" class="form-control" />
                <span asp-validation-for="Products.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Products.Price" class="control-label"></label>
                <input asp-for="Products.Price" class="form-control" />
                <span asp-validation-for="Products.Price" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Products.IsExpired" /> @Html.DisplayNameFor(model => model.Products.IsExpired)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Products.CategoryId" class="control-label"></label>
                <select asp-for="Products.CategoryId" class="form-control" asp-items="@(new SelectList(Model.Categories, "CategoryId", "Id"))"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DiamondStore/DiamondStore/Pages/Products/Delete.cshtml
@page
@model DiamondStore.Pages.Products.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.IsExpired)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.IsExpired)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Category.CategoryId)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Product.ProductId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

DiamondStore/DiamondStore/Pages/Products/Details.cshtml
@page
@model DiamondStore.Pages.Products.DetailsModel

@{
    ViewData["Title"] = "Product Details";
}

<div class="container mx-auto mt-8">
    <h1 class="text-3xl font-bold mb-6">Product Details</h1>
    <div class="bg-white shadow-md rounded-lg p-6">
        <h2 class="text-2xl font-semibold mb-4">Product</h2>
        <hr class="mb-4" />
        @{
            var userRole = HttpContext.Session.GetInt32("UserRole");
        }
        <dl class="grid grid-cols-1 md:grid-cols-2 gap-x-4 gap-y-2">
            <dt class="font-medium">ID</dt>
            <dd class="mb-2">@Html.DisplayFor(model => model.Product.Id)</dd>

            <dt class="font-medium">Name</dt>
            <dd class="mb-2">@Html.DisplayFor(model => model.Product.Name)</dd>

            <dt class="font-medium">Description</dt>
            <dd class="mb-2">@Html.DisplayFor(model => model.Product.Description)</dd>

            <dt class="font-medium">Price</dt>
            <dd class="mb-2">@Html.DisplayFor(model => model.Product.Price)</dd>

            <dt class="font-medium">Is Expired</dt>
            <dd class="mb-2">@Html.DisplayFor(model => model.Product.IsExpired)</dd>

            <dt class="font-medium">Category</dt>
            <dd class="mb-2">
                @* <div>
                <strong>Category ID:</strong> @Html.DisplayFor(model => model.Product.Category.CategoryId)
                </div>
                <div>
                <strong>Internal ID:</strong> @Html.DisplayFor(model => model.Product.Category.Id)
                </div> *@
                <div>
                    <strong>GIA Certificate:</strong> @Html.DisplayFor(model => model.Product.Category.GiaCertificate)
                </div>
                <div>
                    <strong>Cut:</strong> @Html.DisplayFor(model => model.Product.Category.Cut)
                </div>
                <div>
                    <strong>Color:</strong> @Html.DisplayFor(model => model.Product.Category.Color)
                </div>
                <div>
                    <strong>Clarity:</strong> @Html.DisplayFor(model => model.Product.Category.Clarity)
                </div>
                <div>
                    <strong>Carat:</strong> @Html.DisplayFor(model => model.Product.Category.Carat)
                </div>
                @* <div>
                <strong>Distributor ID:</strong> @Html.DisplayFor(model => model.Product.Category.DistributorId)
                </div> *@
            </dd>
            @if (Model.Product.Category.Distributor != null)
            {
                <dt class="font-medium">Distributor</dt>
                <dd class="mb-2">
                    <div>
                        <strong>Distributor Name:</strong> @Html.DisplayFor(model => model.Product.Category.Distributor.DistributorName)
                    </div>
                    <div>
                        <strong>Locate:</strong> @Html.DisplayFor(model => model.Product.Category.Distributor.Locate)
                    </div>
                </dd>
            }
        </dl>
    </div>
    <div class="mt-4">
        @if (userRole == 3)
        {
            <a class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" asp-page="./Edit" asp-route-id="@Model.Product.ProductId">Edit</a>
        }
        <a class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded ml-2" asp-page="./Index">Back to List</a>
    </div>
</div>

DiamondStore/DiamondStore/Pages/Products/Index.cshtml
@page
@model DiamondStore.Pages.Products.IndexModel

@{
    ViewData["Title"] = "Products";
}


@{
    var userRole = HttpContext.Session.GetInt32("UserRole");
}

<section class="container mx-auto px-4">
    <div class="sm:flex sm:items-center sm:justify-between">
        <div>
            <div class="flex items-center gap-x-3">
                <h2 class="text-2xl font-bold text-gray-800 ">Products</h2>
            </div>
            <p class="mt-1 text-sm text-gray-500">These products has been created.</p>
        </div>
        @if (userRole == 3)
        {
            <div class="mb-4">
                <a class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" asp-page="Create">Create New</a>
            </div>
        }
    </div>

    <div class="mt-8 grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4">
        @foreach (var item in Model.Products)
        {
            <div class="w-full max-w-sm rounded-xl border border-gray-200 bg-white shadow px-2">
                <div class="flex flex-col items-center py-6">
                    <img class="mb-3 h-24 w-24 rounded-full p-4 shadow-lg" src="https://th.bing.com/th/id/OIP.7Hw4Ny61e_zegbB2XHQXHwHaFj?rs=1&pid=ImgDetMain" />
                    <h5 class="mb-1 text-xl font-medium text-gray-900 text-center">@Html.DisplayFor(modelItem => item.Name)</h5>
                    <span class="flex items-center gap-1 text-sm text-gray-500">
                        @Html.DisplayFor(modelItem => item.Description)
                    </span>
                    <span class="flex items-center gap-1 text-sm text-gray-500">
                        Price: @Html.DisplayFor(modelItem => item.Price)
                    </span>
                    <span class="flex items-center gap-1 text-sm text-gray-500">
                        Carat: @Html.DisplayFor(modelItem => item.Category.Carat)
                    </span>
                    <div class="mt-4 flex md:mt-6">
                        @if (userRole == 3)
                        {
                            <a class="text-blue-500 hover:text-blue-700" asp-page="./Edit" asp-route-id="@item.ProductId">Edit</a>
                            <span class="mx-2">|</span>
                            <a class="text-red-500 hover:text-red-700" asp-page="./Delete" asp-route-id="@item.ProductId">Delete</a>
                            <span class="mx-2">|</span>
                        }
                        <a class="text-green-500 hover:text-green-700" asp-page="./Details" asp-route-id="@item.ProductId">Details</a>
                        <span class="mx-2">|</span>
                        @if (userRole == 1)
                        {
                            <form method="post" asp-page-handler="AddToCart" asp-route-id="@item.ProductId" class="inline">
                                <button type="submit" class="text-yellow-500 hover:text-yellow-700">Add to Cart</button>
                            </form>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="mt-6 flex items-center justify-between">
        <button class="rounded-md border bg-white px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">
            Previous
        </button>
        <div class="flex items-center space-x-2">
            <button class="rounded-md border bg-white px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">1</button>
            <button class="rounded-md border bg-white px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">2</button>
            <button class="rounded-md border bg-white px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">3</button>
        </div>
        <button class="rounded-md border bg-white px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Next</button>
    </div>
</section>


<script src="https://cdn.tailwindcss.com"></script>